### PR TITLE
Add support for FreeBSD

### PR DESCRIPTION
**Pull request by kikuchan**
...and, make it easy to support additional UNIX-like systems for the future.

### CODE REVIEW

**Comment by evanw** [comment]
Thanks for putting this together. I understand why you refactored it this way, but I'd like to avoid metaprogramming in the makefile because I find it hard to read. I'll gladly accept the rest of the PR though. Feel free to remove the metaprogramming yourself, or I'm also happy to land it as-is and remove the metaprogramming myself afterwards if you prefer. Just let me know.

Also, can you confirm that you have tested esbuild's bundling functionality on both `freebsd/amd64` and `freebsd/arm64` and that it works correctly? I am unable to test this myself so this will be an unsupported build configuration, but I want to make sure someone else at least verifies that it works correctly before I start publishing builds.

**Comment by kikuchan** [comment]
Thank you for the review.
I've removed the metaprogramming in the Makefile, but still try to put them together by using `platform-unixlike`. How about this?

I've also tested by running `make test-all` on `freebsd/amd64` natively and `freebsd/arm64` by using qemu, and they said all passed. Of course a generated executable works fine so far.

**Comment by evanw** [comment]
That's great, thanks! And I appreciate you taking the time to test it.

**Comment by evanw** [comment]
I tried to publish it but npm's publish command failed because of their aggressive package name spam detector. I have reached out to npm support and will try to publish again once the name has been unblocked.

**Comment by kikuchan** [comment]
Oh, ok. I'm waiting for it.
Anyway, thank you for merging!

**Comment by evanw** [comment]
The [esbuild-freebsd-64](https://www.npmjs.com/package/esbuild-freebsd-64) package has now been published (version 0.5.24).

**Comment by kikuchan** [comment]
Thank you! I confirmed it works perfectly via `npm install`. I really appreciate it.

**Pull request merged**
